http:
  host: ""
  port: 8080
  read_timeout: "1s"
  # write_timeout should be very long, for SSE to work properly
  write_timeout: "2h"
  allowed_origins:
    - "*"
  allowed_headers: 
    - "*"
  template_home: "./cmd/http/templates/home.html"
  template_room: "./cmd/http/templates/room.html"
  template_error: "./cmd/http/templates/error.html"

rooms:
  capacity: 100